// File autogenerated on date %INFO%

// Set current language
make.setLanguage('C');

make.entryFile = "main.c"; // main file path
make.out = "vv"; // output file name

// Compile secondary objects in 'build' folder (Default: false)
make.useBuildFolder(true); 

// Flags for linking process
make.linkingFlags = "-std=c99 -g -O3 -D_GNU_SOURCE"

// Enable warnings
make.enableWarning('all');
// make.enableWarning('extra', 'pedantic', 'no-pointer-arith', 'no-unused-result', 'no-unused-parameter'); 



// Flags for all objects
make.flags = "-lpcre -ltermbox -llua5.3";
// make.flags += '-otherflags'

make.include("."); // Includes .h files in root directory
// make.include(["example1/include", "example2/include" ]); // It appends new paths

// compileObjects - Syntax examples:
// libs/mylib.c		Compile the file mylib.c in libs directory
// *.c 				Compile all .c files in the root directory of the project
// */*.c.cpp 		Compile all .c and .cpp files recursively
// libs/*/*			Compile all files recursively in "libs" directory
// 
// You could use the function more times
// It excludes automatically the entry point file
make.compileFiles("*/*.c"); 


function start() {
    make.compile();
}

function clear() {
	make.clear();
}

///
/// JSON Data
///
/// jsonData is a not-currently-used variable usable in the future for saving project's related
/// auto generated data.

jsonData = {
    
};