// File autogenerated on date %INFO%

// Set current language
make.setLanguage('C');

make.entryFile = "main.c"; // main file path
make.out = "vv"; // output file name

// Compile secondary objects in 'build' folder (Default: false)
make.useBuildFolder(true); 

// Set flags
make.flags = "-std=c99 -Wall -Wextra -pedantic -Wno-pointer-arith -Wno-unused-result -Wno-unused-parameter -g -O3 -D_GNU_SOURCE";
make.addFlags("-lpcre -ltermbox -llua5.3"); // Dynamic libraries (it appends them to make.flags property)

make.include("."); // Includes .h files in root directory
// make.include(["example1/include", "example2/include" ]); // It appends new paths

// compileObjects - Syntax examples:
// libs/mylib.c		Compile the file mylib.c in libs directory
// *.c 				Compile all .c files in the root directory of the project
// */*.c.cpp 		Compile all .c and .cpp files recursively
// libs/*/*			Compile all files recursively in "libs" directory
// 
// You could use the function more times
// It excludes automatically the entry point file
make.compileObjects("*/*.h"); 


function start() {
    make.compile();
}

function clear() {
	make.clear();
}

///
/// JSON Data
///

jsonData = {
    
};