// File autogenerated on date %INFO%

var flags = "-std=c99 -Wall -Wextra -pedantic -Wno-pointer-arith -Wno-unused-result -Wno-unused-parameter -g -O3 -D_GNU_SOURCE";

function main() {
    // Write here your code
    make.test();
}